Update CI test scripts (with respect to vitest CLI): * Omit test reports in the CI (in vitest scripts) * Comment out the 'dorny/test-report' CI step (as it's currently not working) * TODO: Set up test reporting for CI and reinstate the workflow steps we have it working properly

diff --git a/.github/workflow.templates/build.yml b/.github/workflow.templates/build.yml
--- a/.github/workflow.templates/build.yml
+++ b/.github/workflow.templates/build.yml
@@ -31,8 +31,8 @@ jobs:
         run: |
           cd packages/client && NODE_OPTIONS="--max-old-space-size=8192" rushx build:prod | tee build.output
           echo "BUILD_STATS<<EOF" >> $GITHUB_ENV
-          # Select all lines starting with 'dist/' from build.output (those are the lines reporting the build file sizes)
-          # And store for use in later steps
+          #! Select all lines starting with 'dist/' from build.output (those are the lines reporting the build file sizes)
+          #! And store for use in later steps
           cat build.output|awk '/^dist\// {print}' >> $GITHUB_ENV
           echo "EOF" >> $GITHUB_ENV
         env:
@@ -65,19 +65,19 @@ jobs:
         if: steps.has_secret.outputs.HAS_SECRETS
         run: |
           set -e
-          # Deploy the preview to firebase hosting, passing the current git branch to be used for the name
-          # of the preview channel
+          #! Deploy the preview to firebase hosting, passing the current git branch to be used for the name
+          #! of the preview channel
           firebase --project eisbuk hosting:channel:deploy ${GITHUB_REF_SLUG_URL:-dev} --token ${{ secrets.FIREBASE_SERVICE_ACCOUNT_EISBUK }} | tee deploy.output
-          # To pass the info to a later task, use the $GITHUB_ENV file
-          # This horrible contraption converts lines like
-          # ✔  hosting:channel: Channel URL (igorice): https://igorice--dev-n0jjvnkh.web.app [expires 2022-03-29 13:10:04] [version a47ca837c7966792]
-          # ✔  hosting:channel: Channel URL (eisbuk): https://eisbuk--dev-xjkubzx5.web.app [expires 2022-03-29 13:10:04] [version 6638d82269ac0062]
-          # to a form like this:
-          # igorice=https://igorice--dev-n0jjvnkh.web.app
-          # eisbuk=https://eisbuk--dev-xjkubzx5.web.app
-          # suitable to be included in the $GITHUB_ENV file
+          #! To pass the info to a later task, use the $GITHUB_ENV file
+          #! This horrible contraption converts lines like
+          #! ✔  hosting:channel: Channel URL (igorice): https://igorice--dev-n0jjvnkh.web.app [expires 2022-03-29 13:10:04] [version a47ca837c7966792]
+          #! ✔  hosting:channel: Channel URL (eisbuk): https://eisbuk--dev-xjkubzx5.web.app [expires 2022-03-29 13:10:04] [version 6638d82269ac0062]
+          #! to a form like this:
+          #! igorice=https://igorice--dev-n0jjvnkh.web.app
+          #! eisbuk=https://eisbuk--dev-xjkubzx5.web.app
+          #! suitable to be included in the $GITHUB_ENV file
           cat deploy.output | grep 'Channel URL' | grep 'hosting:channel:.*https://'|sed -e "s/\x1b\[[0-9;]*m//g;s|.*(||;s|)[^h]*|=|;s/.\[.*//" >> $GITHUB_ENV
-          # documented here: https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
+          #! documented here: https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
       - name: Populate job summary with URLs
         run: |
           echo Preview channels deployed: >> $GITHUB_STEP_SUMMARY
@@ -98,37 +98,44 @@ jobs:
       -  #@ rush_build()
       - name: Run tests
         run: cd packages/client && rushx test:emulators:ci
-      -  #@ check_secrets()
-      - name: Test Report
-        uses: dorny/test-reporter@v1
 
-        #! Do not run on cancelled or if secrets are not available; run in all other cases
-        if: steps.has_secret.outputs.HAS_SECRETS && (success() || failure())
+      #! TODO: The test reporting is currently broken (until we figure our how to do it with vitest),
+      #! so the following block is commented out as to not produce failing checks and gives us a working subset
+      #! of the workflow (and that is purely tests passing or not). We should definitely uncomment this and find
+      #! a way to reinstate it in out workflow.
 
-        with:
-          name: JEST Tests
-          path: packages/client/junit.xml
-          reporter: jest-junit
-      - name: Coveralls
-        uses: coverallsapp/github-action@master
-        if: steps.has_secret.outputs.HAS_SECRETS
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          path-to-lcov: packages/client/coverage/lcov.info
-          base-path: packages/client/
-          flag-name: run-jest
-          parallel: true
-      -  #@ install_gcloud_credentials()
-      -  #@ set_results_destination()
-      -  #@ install_rclone()
-      - name: Copy test results to gcloud
-        if: (success() || failure()) && steps.has_secret.outputs.HAS_SECRETS
-        run: |
-          rclone copy packages/client/coverage gcloud:cypress-logs-bucket/${{ steps.results-destination.outputs.RESULTS_DESTINATION }}/coverage --log-level INFO
-      - name: Print gcloud url to view test results
-        if: (success() || failure()) && steps.has_secret.outputs.HAS_SECRETS
-        run: |
-          echo Check out coverage results at https://storage.googleapis.com/cypress-logs-bucket/${{ steps.results-destination.outputs.RESULTS_DESTINATION }}/coverage/lcov-report/index.html
+      #! -  #@ check_secrets()
+      #! - name: Test Report
+      #!   uses: dorny/test-reporter@v1
+
+      #!   #! Do not run on cancelled or if secrets are not available; run in all other cases
+      #!   if: steps.has_secret.outputs.HAS_SECRETS && (success() || failure())
+
+      #!   with:
+      #!     name: JEST Tests
+      #!     path: packages/client/junit.xml
+      #!     reporter: jest-junit
+      #! - name: Coveralls
+      #!   uses: coverallsapp/github-action@master
+      #!   if: steps.has_secret.outputs.HAS_SECRETS
+      #!   with:
+      #!     github-token: ${{ secrets.GITHUB_TOKEN }}
+      #!     path-to-lcov: packages/client/coverage/lcov.info
+      #!     base-path: packages/client/
+      #!     flag-name: run-jest
+      #!     parallel: true
+      #! -  #@ install_gcloud_credentials()
+      #! -  #@ set_results_destination()
+      #! -  #@ install_rclone()
+      #! - name: Copy test results to gcloud
+      #!   if: (success() || failure()) && steps.has_secret.outputs.HAS_SECRETS
+      #!   run: |
+      #!     rclone copy packages/client/coverage gcloud:cypress-logs-bucket/${{ steps.results-destination.outputs.RESULTS_DESTINATION }}/coverage --log-level INFO
+      #! - name: Print gcloud url to view test results
+      #!   if: (success() || failure()) && steps.has_secret.outputs.HAS_SECRETS
+      #!   run: |
+      #!     echo Check out coverage results at https://storage.googleapis.com/cypress-logs-bucket/${{ steps.results-destination.outputs.RESULTS_DESTINATION }}/coverage/lcov-report/index.html
+
   run-lint:
     name: Lint source
     runs-on: ubuntu-latest
