Remove pre-commit, replace pre-commit job with lint job

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -122,20 +122,20 @@ jobs:
           key: ${{ runner.os }}-modules-emulators-v12-${{ hashFiles('**/yarn.lock') }}
       - name: Install and link packages
         run: ./eisbuk-install.sh
-      - name: Run lint
+      - name: Lint client app
         run: "yarn --cwd eisbuk-admin lint:strict"
+      - name: Lint eisbuk-shared
+        # Do not run on cancelled; run in all other cases
+        # We don't want a failed prevoius lint step to make this step not run
+        if: success() || failure() 
+        run: "yarn --cwd eisbuk-shared lint:strict"
+      - name: Lint the functions
+        # Do not run on cancelled; run in all other cases
+        # We don't want a failed prevoius lint step to make this step not run
+        if: success() || failure() 
+        run: "yarn --cwd eisbuk-admin/functions lint:strict"
       - name: Typecheck the functions
-        if: success() || failure() # Do not run on cancelled; run in all other cases
-        # We don't want a failed lint step to make this step not run
+        # Do not run on cancelled; run in all other cases
+        # We don't want a failed lint steps to make this step not run
+        if: success() || failure() 
         run: "yarn --cwd eisbuk-admin/functions typecheck"
-
-  pre-commit:
-    runs-on: ubuntu-latest
-
-    steps:
-      - uses: actions/checkout@v2
-      - uses: actions/setup-python@v2
-        with:
-          python-version: "3.7"
-          architecture: "x64"
-      - uses: pre-commit/action@v2.0.0
